@startgantt Gantt_1
scale 2
printscale weekly

project starts the 2021/01/14
2021/06/20 is closed

'Dokumentazioa'
[Dokumentazioa - Webgunea] starts 2021/01/14 and ends 2021/06/20
[Dokumentazioa - Memoria] starts 2021/01/14 and ends 2021/06/20
[Dokumentazioa - Aurkezpena] starts 2021/05/12 and ends 2021/06/20
[Dokumentazioa - Posterra] starts 2021/05/12 and ends 2021/06/20
[Dokumentazioa - Webgunea] is colored in Blue
[Dokumentazioa - Memoria] is colored in Blue
[Dokumentazioa - Aurkezpena] is colored in Blue
[Dokumentazioa - Posterra] is colored in Blue

'Memoriaren Eranskinak'
[Memoriaren Eranskinak - OpenUP] starts 2021/01/14 and ends 2021/06/20
[Memoriaren Eranskinak - CCII-2016N-02] starts 2021/01/14 and ends 2021/06/20
[Memoriaren Eranskinak - Sistemaren Espezifikazioa] starts 2021/01/14 and ends 2021/03/15
[Memoriaren Eranskinak - OpenUP] is colored in Orange
[Memoriaren Eranskinak - CCII-2016N-02] is colored in Orange
[Memoriaren Eranskinak - Sistemaren Espezifikazioa] is colored in Orange

'Barne Kudeaketa'
[Barne Kudeaketa - Plangintza] starts 2021/01/14 and ends 2021/06/20
[Barne Kudeaketa - Jarraipen eta Kontrola] starts 2021/01/14 and ends 2021/06/20
[Barne Kudeaketa - Plangintza] is colored in Green
[Barne Kudeaketa - Jarraipen eta Kontrola] is colored in Green

'ModelEditor'
[ModelEditor - OpenUP Eredua] starts 2021/01/14 and ends 2021/03/15
[ModelEditor - Editore Grafikoa] starts 2021/01/14 and ends 2021/03/15
[ModelEditor - Testu Editorea] starts 2021/01/14 and ends 2021/03/15
[ModelEditor - OpenUP Eredua] is colored in Red
[ModelEditor - Editore Grafikoa] is colored in Red
[ModelEditor - Testu Editorea] is colored in Red

'IO-System'
[IO-System - Datu Basea] starts 2021/03/16 and ends 2021/06/20
[IO-System - Web Interfazea] starts 2021/03/16 and ends 2021/06/20
[IO-System - Web Kodea] starts 2021/03/16 and ends 2021/06/20
[IO-System - Datu Basea] is colored in Yellow
[IO-System - Web Interfazea] is colored in Yellow
[IO-System - Web Kodea] is colored in Yellow

[ModelEditor - OpenUP Eredua] -> [IO-System - Datu Basea]
[ModelEditor - OpenUP Eredua] -> [IO-System - Web Interfazea]
[ModelEditor - OpenUP Eredua] -> [IO-System - Web Kodea]
@endgantt