@startwbs LDE
* ProMeta
**[#DodgerBlue] Dokumentazioa
***[#DodgerBlue] Webgunea
***[#DodgerBlue] Memoria
***[#DodgerBlue] Aurkezpena
***[#DodgerBlue] Posterra
**[#orange] Memoriaren Eranskinak
***[#orange] OpenUP
***[#orange] CCII-2016N-02
***[#orange] Sistemaren Espezifikazioa
**[#LimeGreen] Barne Kudeaketa
***[#LimeGreen] Plangintza
***[#LimeGreen] Jarraipen eta Kontrola
**[#OrangeRed] ModelEditor
***[#OrangeRed] OpenUP Eredua
***[#OrangeRed] Editore Grafikoa
***[#OrangeRed] Testu Editorea
**[#yellow] IO-System
***[#yellow] Datu Basea
***[#yellow] Web Interfazea
***[#yellow] Web Kodea
@endwbs