<?php 

	/**
	* @file
	* Contains \Drupal\post_data\Controller\PostDataController
	*/

	namespace Drupal\post_data\Controller;
	use Drupal\Core\Database\Database;
	use \Mpdf\Mpdf;
	use Mpdf\MpdfException;

	class PostDataController{
		
		
		public function updateProjectArtifact($project_id,$phase_id,$activity_id,$task_id,$artifact_id){
			
			$version = \Drupal::request()->request->get('version'); 
			$hours = \Drupal::request()->request->get('hours'); 
			$assessment_editor = \Drupal::request()->request->get('assessment_editor'); 
			
			Database::setActiveConnection('process_db');
			$database = Database::getConnection();
			$database->query(
				"update project_artifacts 
				set version='{$version}',hours={$hours},assessment_editor={$assessment_editor}
				where project_id='{$project_id}' AND phase_id='{$phase_id}' AND activity_id='{$activity_id}' AND task_id ='{$task_id}' AND artifact_id='{$artifact_id}'"
			);
			Database::setActiveConnection();
		}
		
		public function insertIntoDocumentalDB($project_id,$phase_id,$activity_id,$task_id,$artifact_id){
			
			
			Database::setActiveConnection('process_db');
			$database = Database::getConnection();
			$result = $database->query("select * from artifact_sections where artifact_id='{$artifact_id}'");
			Database::setActiveConnection();
			
			Database::setActiveConnection('document_db');
			$database = Database::getConnection();
			
			$result2 = $database->query("select * from documents where project_id='{$project_id}' AND id='{$artifact_id}'");
			$row2 = $result2->fetchAssoc();
			if(empty($row2)){
				$database->query("insert into documents (project_id,id) values({$project_id},{$artifact_id})");
			}
			
			while($row = $result->fetchAssoc()){
				$aux = explode('.',$row['section_number']);
				$number = $aux[0] . '-' . $aux[1];
				$content = \Drupal::request()->request->get($number); 
				$result3 = $database->query(
					"update sections set content='{$content}' where project_id='{$project_id}' and document_id={$artifact_id} and section_number LIKE {$row['section_number']}"
				);
				$result3->allowRowCount = TRUE;
				if ($result3->rowCount()==0){
					$database->query(
						"insert into sections values ({$project_id},{$artifact_id},{$row['section_number']},'{$content}')"
					);
				}
			}
			Database::setActiveConnection();
			
			
			
		}
		
		public function generatePDF($project_id,$artifact_id){
			
			$mpdf = new \Mpdf\Mpdf();
			
			$html=	'';
	
			Database::setActiveConnection('process_db');
			$database = Database::getConnection();
			$resultA = $database->query("select * from artifacts where id='{$artifact_id}'");
			$resultB = $database->query("select * from projects where id='{$project_id}'");
			$rowA = $resultA->fetchAssoc();
			$rowB = $resultB->fetchAssoc();
			
			$artifact_name = $rowA['name'];
			$project_name = $rowB['name'];
			
			$mpdf->SetHeader('Project: ' . $project_name . '||Last change: '. date('Y-m-d H:i:s')); //Header
			
			$mpdf->SetFooter('Document generated by ProWF||{PAGENO}'); //Footer
			
			$html .= '<h1 style="text-align: center;">' . $artifact_name . '</h1><br>'; //Main title - Document name
			
			
			$result = $database->query("select * from artifact_sections where artifact_id='{$artifact_id}'");
			Database::setActiveConnection();
			
			Database::setActiveConnection('document_db');
			$database = Database::getConnection();
			
			while($row = $result->fetchAssoc()){
				$result2 = $database->query("select * from sections where project_id={$project_id} and document_id={$artifact_id} and section_number LIKE {$row['section_number']}"); 
				$row2 = $result2->fetchAssoc();
				
				$html .= '<h3>' . $row['section_number'] . '. ' . $row['section_name'] . '</h3>'; //Sub title - Section number and name 
				$html .= '<p>' . $row2['content'] . '</p><br>'; //Paragraph - Section content
			}

			// Write HTML code into PDF
			$mpdf->WriteHTML($html);

			$filename = $artifact_name . '.pdf';
			$filepath = $project_name .'/docs/' . $filename ;
			
			// Output a PDF file directly to the browser
			$mpdf->Output('public://' . $filepath,'F');
		   
			
			$result = $database->query("UPDATE documents SET file_path='{$filename}' WHERE project_id='{$project_id}' and id='{$artifact_id}'");
			Database::setActiveConnection();
				
			
		   
			return $filename . ';' . $filepath;
		}
	   
		public function test(){
		   
		    $project_id = \Drupal::request()->query->get('project'); //GET PROJECT ID FROM URL
			$phase_id = \Drupal::request()->query->get('p_id'); //GET PHASE ID FROM URL
			$activity_id = \Drupal::request()->query->get('a_id'); //GET ACTIVITY ID FROM URL
			$task_id = \Drupal::request()->query->get('t_id'); //GET TASK ID FROM URL
			$artifact_id = \Drupal::request()->query->get('id'); //GET ARTIFACT ID FROM URL
			
			$this->updateProjectArtifact($project_id,$phase_id,$activity_id,$task_id,$artifact_id); //UPDATE project_artifacts TABLE
			
			$this->insertIntoDocumentalDB($project_id,$phase_id,$activity_id,$task_id,$artifact_id); //INSERT SECTION CONTENTS INTO DOCUMENTAL DB (section table)
	
			$documentAux = $this->generatePDF($project_id,$artifact_id);
			$version = \Drupal::request()->request->get('version'); 
			$document = $documentAux . ';' . $version;
			
			drupal_flush_all_caches();
			
			drupal_set_message('Section content saved in the database');
			drupal_set_message('PDF file generated');
			
			
			return array(
				'#theme' => 'indexPD',
				'#document' => $document
	
			);
			
			
		}
		  
		  
	}

