@startuml Arkitektura_ModelEditor
!include <logos/mysql>
!include <logos/eclipse>

component "<$eclipse>\nEPF Composer" as EPFComposer
component Importer
component "<$eclipse>\nText Editor" as TextEditor
component Synchronizer
component "<$eclipse>\nGraphic Editor" as GraphicEditor
component Exporter
database "<$mysql>\nDatabase" as Database

EPFComposer -> Importer
Importer -> GraphicEditor
GraphicEditor <-> Synchronizer
Synchronizer <-> TextEditor
GraphicEditor -> Exporter
Exporter -> Database
@enduml