@startuml UCM_ModelEditor
left to right direction

actor "Process Engineer" as ProcessEngineer

rectangle "EPF Composer" as EPFComposer {
    usecase "Import Library" as ImportLibrary
    usecase "Export Library" as ExportLibrary
    usecase "Edit Library" as EditLibrary
    usecase "Publish Website" as PublishWebsite
}

rectangle Eclipse {
    usecase "Transform Model" as TransformModel
    usecase "Edit Text Model" as EditTextModel
    usecase "Edit Graphical Model" as EditGraphicalModel
    usecase "Create Text Model" as CreateTextModel
    usecase "Create Graphical Model" as CreateGraphicalModel
    usecase "Create SQL" as CreateSQL
}

ProcessEngineer --> ImportLibrary
ProcessEngineer --> ExportLibrary
ProcessEngineer --> EditLibrary
ProcessEngineer --> PublishWebsite
ProcessEngineer --> TransformModel
ProcessEngineer --> EditTextModel
ProcessEngineer --> EditGraphicalModel
ProcessEngineer --> CreateTextModel
ProcessEngineer --> CreateGraphicalModel
ProcessEngineer --> CreateSQL
@enduml