@startuml UCM_IO-System
left to right direction

actor Anonymous
actor Authenticated
actor Administrator

rectangle Administration {
    usecase "Add Role" as AddRole
    usecase "Remove Role" as RemoveRole
    usecase "Change Permissions" as ChangePermissions
}

rectangle Authentication {
    usecase "Log In" as LogIn
    usecase "Log Out" as LogOut
    usecase "Create Account" as CreateAccount
    usecase "View Account" as ViewAccount
    usecase "Edit Account" as EditAccount
    usecase "Reset Password" as ResetPassword
}

rectangle Content {
    usecase "Search Content" as SearchContent
    usecase "View Content" as ViewContent
    usecase "Edit Content" as EditContent
    usecase "Add Content" as AddContent
}

Anonymous --> LogIn
Anonymous --> CreateAccount
Anonymous --> ResetPassword
Anonymous --> SearchContent
Anonymous --> ViewContent

Authenticated --> LogOut
Authenticated --> ViewAccount
Authenticated --> EditAccount
Authenticated --> SearchContent
Authenticated --> ViewContent
Authenticated --> EditContent
Authenticated --> AddContent

Administrator --> AddRole
Administrator --> RemoveRole
Administrator --> ChangePermissions
@enduml