/* --- menu items --- */
var TREE_ITEMS =
	[
		['ProMeta Proiektua', '../main/home_page.html',
			['Portada', '../Proiektua/Portada.pdf'],
			['Laburpen Posterra', '../Proiektua/Laburpen Posterra.pdf'],
			['Aurkezpena', '../Proiektua/Aurkezpena.pdf'],
			['Dokumentazioaren Kontrola', '../Proiektua/Dokumentazioaren Kontrola.pdf'],
			['Aurkibide Orokorra', '../Proiektua/Aurkibide Orokorra.pdf'],
			['Memoria', '../Proiektua/Memoria/Memoria.pdf',
				['M1 - Sarrera', '../Proiektua/Memoria/M1 - Sarrera.pdf'],
				['M2 - Helburua', '../Proiektua/Memoria/M2 - Helburua.pdf'],
				['M3 - Aurrekariak', '../Proiektua/Memoria/M3 - Aurrekariak.pdf'],
				['M4 - Egungo Egoera', '../Proiektua/Memoria/M4 - Egungo Egoera.pdf',
					['M4.1 - Egungo Egoeraren Deskribapena', '../Proiektua/Memoria/M4 - Egungo Egoera.pdf'],
					['M4.2 - Identifikatutako Hutsuneen Laburpena', '../Proiektua/Memoria/M4 - Egungo Egoera.pdf']
				],
				['M5 - Arauak eta Erreferentziak', '../Proiektua/Memoria/M5 - Arauak eta Erreferentziak.pdf',
					['M5.1 - Aplikatutako Legedia eta Araudia', '../Proiektua/Memoria/M5 - Arauak eta Erreferentziak.pdf'],
					['M5.2 - Bibliografia', '../Proiektua/Memoria/M5 - Arauak eta Erreferentziak.pdf'],
					['M5.3 - Metodoak, Tresnak, Ereduak, Metrikak eta Prototipoak', '../Proiektua/Memoria/M5 - Arauak eta Erreferentziak.pdf',
						['M5.3.1 - Metodoak eta Tresnak', '../Proiektua/Memoria/M5 - Arauak eta Erreferentziak.pdf'],
						['M5.3.2 - Ereduak, Metrikak eta Prototipoak', '../Proiektua/Memoria/M5 - Arauak eta Erreferentziak.pdf']
					],
					['M5.4 - Idazketaren Kalitatearen Kudeaketa Plana', '../Proiektua/Memoria/M5 - Arauak eta Erreferentziak.pdf'],
					['M5.5 - Beste Erreferentziak', '../Proiektua/Memoria/M5 - Arauak eta Erreferentziak.pdf']
				],
				['M6 - Definizioak eta Laburdurak', '../Proiektua/Memoria/M6 - Definizioak eta Laburdurak.pdf'],
				['M7 - Hasierako Betekizunak', '../Proiektua/Memoria/M7 - Hasierako Betekizunak.pdf'],
				['M8 - Irismena', '../Proiektua/Memoria/M8 - Irismena.pdf'],
				['M9 - Hipotesiak eta Murriztapenak', '../Proiektua/Memoria/M9 - Hipotesiak eta Murriztapenak.pdf'],
				['M10 - Aukeren Azterketa eta Bideragarritasuna', '../Proiektua/Memoria/M10 - Aukeren Azterketa eta Bideragarritasuna.pdf'],
				['M11 - Proposatutako Sistemaren Deskribapena', '../Proiektua/Memoria/M11 - Proposatutako Sistemaren Deskribapena.pdf'],
				['M12 - Arriskuen Analisia', '../Proiektua/Memoria/M12 - Arriskuen Analisia.pdf'],
				['M13 - Proiektuaren Antolamendua eta Kudeaketa', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf',
					['M13.1 - Proiektuaren Antolamendua', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf',
						['M13.1.1 - Proiektuaren Aktoreak eta Erlazioak', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf'],
						['M13.1.2 - Barne Egitura', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf'],
						['M13.1.3 - Kanpo Interfazeak', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf'],
						['M13.1.4 - Rolak eta Ardurak', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf']
					],
					['M13.2 - Proiektuaren Kudeaketa', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf',
						['M13.2.1 - Integrazioaren Kudeaketa', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf'],
						['M13.2.2 - Irismenaren Kudeaketa', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf'],
						['M13.2.3 - Epeen Kudeaketa', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf'],
						['M13.2.4 - Produktuaren Kostuen Kudeaketa', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf'],
						['M13.2.5 - Kalitate Kudeaketa', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf'],
						['M13.2.6 - Giza Baliabideen Kudeaketa', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf'],
						['M13.2.7 - Komunikazioen Kudeaketa', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf'],
						['M13.2.8 - Arriskuen Kudeaketa', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf'],
						['M13.2.9 - Erosketen Kudeaketa', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf'],
						['M13.2.10 - Interesatuen Kudeaketa', '../Proiektua/Memoria/M13 - Proiektuaren Kudeaketa eta Antolamendua.pdf'],
					]
				],
				['M14 - Denbora Planifikazioa', '../Proiektua/Memoria/M14 - Denbora Planifikazioa.pdf',
					['M14.1 - Proiektu Planaren Eboluzioa', '../Proiektua/Memoria/M14 - Denbora Planifikazioa.pdf'],
					['M14.2 - Hornitzailearen Proiektu Planaren Ebaluazioa', '../Proiektua/Memoria/M14 - Denbora Planifikazioa.pdf'],
				],
				['M15 - Aurrekontuaren Laburpena', '../Proiektua/Memoria/M15 - Aurrekontuaren Laburpena.pdf'],
				['M16 - Dokumentuen Lehentasun Ordena', '../Proiektua/Memoria/M16 - Dokumentuen Lehentasun Ordena.pdf']
			],
			['Memoriaren Eranskinak', '../Proiektua/Memoriaren Eranskinak/Memoriaren Eranskinak.pdf',
        ['A1 - Sarrerako Dokumentazioa', '../Proiektua/Memoriaren Eranskinak/A1 - Sarrerako dokumentazioa/A1 - Sarrerako dokumentazioa.pdf',
          ['A1.1 - OpenUp 1.0', 'http://www.utm.mx/~caff/doc/OpenUPWeb/index.htm'],
          ['A1.1 - OpenUp 1.5', 'https://download.eclipse.org/technology/epf/OpenUP/published/openup_published_1.5.1.5_20121212/openup/index.htm'],
          ['A1.2 - CCII-N2016-02', '../Proiektua/Memoriaren Eranskinak/A1 - Sarrerako dokumentazioa/CCII-N2016-02.pdf'],
          ['A1.3 - CCII-UNE 157801', '../Proiektua/Memoriaren Eranskinak/A1 - Sarrerako dokumentazioa/CCII-UNE 157801.pdf'],
          ['A1.4 - ProWF Webgunea', '../Barne Informazioa/Aurreko Proiektuen Webguneak/ProWF_Proiektua/index.html'],
          ['A1.5 - ProWF Memoria', '../Proiektua/Memoriaren Eranskinak/A1 - Sarrerako dokumentazioa/JulenRojo_GrAL_Memoria.pdf'],
          ['A1.6 - ProWF Aurkezpena', '../Proiektua/Memoriaren Eranskinak/A1 - Sarrerako dokumentazioa/RojoJulen_GrAL.pdf'],
        ],
				['A2 - Analisia eta Diseinua', '../Proiektua/Memoriaren Eranskinak/A2 - Analisia eta Diseinua/A2 - Analisia eta Diseinua.pdf',
					['A2.1 - Arkitektura Koadernoa', '../Proiektua/Memoriaren Eranskinak/A2 - Analisia eta Diseinua/architecture_notebook_tpl.pdf'],
					['A2.2 - Analisiaren Eredua', '../Proiektua/Memoriaren Eranskinak/A2 - Analisia eta Diseinua/RUP Analysis Model/index.html'],
					['A2.3 - Diseinuaren Eredua', '../Proiektua/Memoriaren Eranskinak/A2 - Analisia eta Diseinua/design_tpl.pdf',
						['A2.3.1 - Interfazeen Diseinua', '../Proiektua/Memoriaren Eranskinak/A2 - Analisia eta Diseinua/design_tpl.pdf'],
						['A2.3.2 - Datu Ereduen Diseinua', '../Proiektua/Memoriaren Eranskinak/A2 - Analisia eta Diseinua/design_tpl.pdf'],
						['A2.3.3 - Inplementazioaren Diseinua', '../Proiektua/Memoriaren Eranskinak/A2 - Analisia eta Diseinua/design_tpl.pdf']
					]
				],
				['A3 - Tamaina eta Esfortzu Estimazioa', '../Proiektua/Memoriaren Eranskinak/A3 - Tamaina eta Esfortzu Estimazioa/A3 - Tamaina eta Esfortzu Estimazioa.pdf'],
				['A4 - Kudeaketa Plana', '../Proiektua/Memoriaren Eranskinak/A4 - Kudeaketa Plana/A4 - Kudeaketa Plana.pdf',
					['A4.1 - Integrazioaren Kudeaketa', '../Proiektua/Memoriaren Eranskinak/A4 - Kudeaketa Plana/A4 - Kudeaketa Plana.pdf'],
					['A4.2 - Irismenaren Kudeaketa', '../Proiektua/Memoriaren Eranskinak/A4 - Kudeaketa Plana/A4 - Kudeaketa Plana.pdf'],
					['A4.3 - Epeen Kudeaketa', '../Proiektua/Memoriaren Eranskinak/A4 - Kudeaketa Plana/A4 - Kudeaketa Plana.pdf'],
					['A4.4 - Produktuaren Kostuen Kudeaketa', '../Proiektua/Memoriaren Eranskinak/A4 - Kudeaketa Plana/A4 - Kudeaketa Plana.pdf'],
					['A4.5 - Kalitate Kudeaketa', '../Proiektua/Memoriaren Eranskinak/A4 - Kudeaketa Plana/A4 - Kudeaketa Plana.pdf'],
					['A4.6 - Giza Baliabideen Kudeaketa', '../Proiektua/Memoriaren Eranskinak/A4 - Kudeaketa Plana/A4 - Kudeaketa Plana.pdf'],
					['A4.7 - Komunikazioen Kudeaketa', '../Proiektua/Memoriaren Eranskinak/A4 - Kudeaketa Plana/A4 - Kudeaketa Plana.pdf'],
					['A4.8 - Arriskuen Kudeaketa', '../Proiektua/Memoriaren Eranskinak/A4 - Kudeaketa Plana/A4 - Kudeaketa Plana.pdf'],
					['A4.9 - Erosketen Kudeaketa', '../Proiektua/Memoriaren Eranskinak/A4 - Kudeaketa Plana/A4 - Kudeaketa Plana.pdf'],
					['A4.10 - Interesatuen Kudeaketa', '../Proiektua/Memoriaren Eranskinak/A4 - Kudeaketa Plana/A4 - Kudeaketa Plana.pdf'],
				],
				['A5 - Segurtasun Plana', '../Proiektua/Memoriaren Eranskinak/A5 - Segurtasun Plana/A5 - Segurtasun Plana.pdf'],
				['A6 - Beste Eranskinak', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/A6 - Beste Eranskinak.pdf',
					['A6.1 - Hedapena', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/0_hedapena.pdf',
						['A6.1.1 - Produktuaren Dokumentazioa', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/Product Documentation.pdf'],
						['A6.1.2 - Laguntza Dokumentazioa', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/Support Documentation.pdf'],
						['A6.1.3 - Erabiltzaile Dokumentazioa', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/User Documentation.pdf'],
						['A6.1.4 - Trebatzeko Materialak', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/Training Materials.pdf'],
						['A6.1.5 - Backout Plana', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/Backout Plan.pdf'],
						['A6.1.6 - Hedapen Plana', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/rup_dplpln_tpl.pdf'],
						['A6.1.7 - Azpiegitura', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/Infrastructure.pdf'],
						['A6.1.8 - Entrega Komunikazioak', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/rup_relnt_tpl.pdf'],
						['A6.1.9 - Entrega Kontrolak', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/Release Controls.pdf',
							['A6.1.9.1 - Pre-Alfa', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/Release Controls.pdf'],
							['A6.1.9.2 - Alfa', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/Release Controls.pdf'],
							['A6.1.9.3 - Beta', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/Release Controls.pdf'],
							['A6.1.9.4 - Definitibo-kandidatua', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/Release Controls.pdf'],
							['A6.1.9.5 - Erabilgarria', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/Release Controls.pdf'],
							['A6.1.9.6 - Ez egonkorra', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/Release Controls.pdf'],
							['A6.1.9.7 - Egonkorra', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/Release Controls.pdf']
						],
						['A6.1.10 - Entrega', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/Release.pdf'],
					],
					['A6.2 - Garapena', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Garapena/0_garapena.pdf',
						['A6.2.1 - Inplementazioa', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Garapena/Implementation.pdf'],
						['A6.2.2 - Build', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Garapena/Build.pdf'],
						['A6.2.3 - Garatzaileen Probak', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Garapena/Developer Tests.pdf'],
						['A6.2.4 - Diseinua', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Garapena/design_tpl.pdf']
					],
					['A6.3 - Ingurunea', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Ingurunea/0_ingurunea.pdf',
						['A6.3.1 - Garapen Kasua', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Ingurunea/development_case_tpl.pdf'],
						['A6.3.2 - Tresnak', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Ingurunea/tools.pdf'],
					],
					['A6.4 - Proba', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Proba/0_probak.pdf',
						['A6.4.1 - Proba Kasuak', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Proba/test_cases_tpl.pdf'],
						['A6.4.2 - Proba Log-ak', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Proba/test_log.pdf'],
						['A6.4.3 - Proba Script-ak', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Proba/test_script_tpl.pdf']
					]
				]
			],
			['Sistemaren Espezifikazioa', '../Proiektua/Sistemaren Espezifikazioa/Sistemaren Espezifikazioa.pdf',
				['1 - Glosategia', '../Proiektua/Sistemaren Espezifikazioa/Glosategia.pdf'],
				['2 - Ikuspegia', '../Proiektua/Sistemaren Espezifikazioa/Ikuspegia.pdf'],
				['3 - Betebeharren Espezifikazioa', '../Proiektua/Sistemaren Espezifikazioa/systemwide_req_spec.pdf'],
				['4 - Erabilpen Kasuak', '../Proiektua/Sistemaren Espezifikazioa/Erabilpen Kasuak/usecase_specification_tpl.pdf',
					['4.1 - Erabilpen Kasua', '../Proiektua/Sistemaren Espezifikazioa/Erabilpen Kasuak/usecase_specification_tpl.pdf']
				],
				['5 - Erabilpen Kasuen Eredua', '../Proiektua/Sistemaren Espezifikazioa/Use Case Model/index.html']
			],
			['Aurrekontua ', '../Proiektua/Aurrekontua/Aurrekontua.pdf',
				['1 - Orokortasunak ', '../Proiektua/Aurrekontua/Aurrekontua.pdf'],
				['2 - Edukia ', '../Proiektua/Aurrekontua/Aurrekontua.pdf']
			],
			['Ikerlanak', '../Proiektua/Ikerlanak/Ikerlanak.pdf',
				['1 - Orokortasunak', '../Proiektua/Ikerlanak/Ikerlanak.pdf'],
				['2 - Edukia', '../Proiektua/Ikerlanak/Ikerlanak.pdf']
			]
		],
		['ProMeta Barne Informazioa', '../Barne Informazioa/Barne Informazioa.pdf',
			['1 - Barne Kudeaketa', '../Barne Informazioa/Barne Kudeaketa/Barne Kudeaketa.pdf',
        ['1.1 - Artefaktuen Txantiloiak PDF', '../Barne Informazioa/Barne Kudeaketa/Artefaktuen Txantiloiak.pdf',
          ['1.1.1 - Arkitektura Koadernoa', '../Proiektua/Memoriaren Eranskinak/A2 - Analisia eta Diseinua/architecture_notebook_tpl.pdf'],
          ['1.1.2 - Diseinuaren Eredua', '../Proiektua/Memoriaren Eranskinak/A2 - Analisia eta Diseinua/design_tpl.pdf'],
          ['1.1.3 - Hedapen Plana', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/rup_dplpln_tpl.pdf'],
          ['1.1.4 - Entrega Komunikazioak', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/rup_relnt_tpl.pdf'],
          ['1.1.5 - Garapen Kasua', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Ingurunea/development_case_tpl.pdf'],
          ['1.1.6 - Proba Kasuak', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Proba/test_cases_tpl.pdf'],
          ['1.1.7 - Proba Script-ak', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Proba/test_script_tpl.pdf'],
          ['1.1.8 - Glosategia', '../Proiektua/Sistemaren Espezifikazioa/rup_glossary.pdf'],
          ['1.1.9 - Ikuspegia', '../Proiektua/Sistemaren Espezifikazioa/vision_tpl.pdf'],
          ['1.1.10 - Betebeharren Espezifikazioa', '../Proiektua/Sistemaren Espezifikazioa/systemwide_req_spec.pdf'],
          ['1.1.11 - Erabilpen Kasua', '../Proiektua/Sistemaren Espezifikazioa/Erabilpen Kasuak/usecase_specification_tpl.pdf'],
          ['1.1.12 - Iterazio Plana', '../Barne Informazioa/Barne Kudeaketa/iteration_plan_tpl.pdf'],
          ['1.1.13 - Proiektu Plana', '../Barne Informazioa/Barne Kudeaketa/project_plan_tpl.pdf'],
          ['1.1.14 - Arrisku Zerrenda', '../Barne Informazioa/Barne Kudeaketa/risk_list_tpl.pdf'],
          ['1.1.15 - Lan Atazen Zerrenda', '../Barne Informazioa/Barne Kudeaketa/work_items_list_tpl.pdf'],
        ],
        ['1.2 - Artefaktuen Txantiloiak DOCX', '../Barne Informazioa/Barne Kudeaketa/Artefaktuen Txantiloiak.pdf',
          ['1.2.1 - Arkitektura Koadernoa', '../Proiektua/Memoriaren Eranskinak/A2 - Analisia eta Diseinua/architecture_notebook_tpl.dotx'],
          ['1.2.2 - Diseinuaren Eredua', '../Proiektua/Memoriaren Eranskinak/A2 - Analisia eta Diseinua/design_tpl.dotx'],
          ['1.2.3 - Hedapen Plana', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/rup_dplpln_tpl.dotx'],
          ['1.2.4 - Entrega Komunikazioak', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Hedapena/rup_relnt_tpl.dotx'],
          ['1.2.5 - Garapen Kasua', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Ingurunea/development_case_tpl.dotx'],
          ['1.2.6 - Proba Kasuak', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Proba/test_cases_tpl.dotx'],
          ['1.2.7 - Proba Script-ak', '../Proiektua/Memoriaren Eranskinak/A6 - Beste Eranskinak/Proba/test_script_tpl.dotx'],
          ['1.2.8 - Glosategia', '../Proiektua/Sistemaren Espezifikazioa/rup_glossary.dotx'],
          ['1.2.9 - Ikuspegia', '../Proiektua/Sistemaren Espezifikazioa/vision_tpl.dotx'],
          ['1.2.10 - Betebeharren Espezifikazioa', '../Proiektua/Sistemaren Espezifikazioa/systemwide_req_spec.dotx'],
          ['1.2.11 - Erabilpen Kasua', '../Proiektua/Sistemaren Espezifikazioa/Erabilpen Kasuak/usecase_specification_tpl.dotx'],
          ['1.2.12 - Iterazio Plana', '../Barne Informazioa/Barne Kudeaketa/iteration_plan_tpl.dotx'],
          ['1.2.13 - Proiektu Plana', '../Barne Informazioa/Barne Kudeaketa/project_plan_tpl.dotx'],
          ['1.2.14 - Arrisku Zerrenda', '../Barne Informazioa/Barne Kudeaketa/risk_list_tpl.xltx'],
          ['1.2.15 - Lan Atazen Zerrenda', '../Barne Informazioa/Barne Kudeaketa/work_items_list_tpl.xltx'],
        ],
				['1.3 - Hizkuntza Hitzarmena', '../Barne Informazioa/Barne Kudeaketa/Hizkuntza Hitzarmena.pdf'],
        ['1.4 - Bilera Aktak', '../Barne Informazioa/Barne Kudeaketa/Bilera Aktak/Bilera Aktak.pdf',
          ['1.4.1 - B1.2020-10-29', '../Barne Informazioa/Barne Kudeaketa/Bilera Aktak/B1.2020-10-29.pdf'],
          ['1.4.2 - B2.2020-11-06', '../Barne Informazioa/Barne Kudeaketa/Bilera Aktak/B2.2020-11-06.pdf'],
          ['1.4.3 - B3.2021-01-15', '../Barne Informazioa/Barne Kudeaketa/Bilera Aktak/B3.2021-01-15.pdf']
        ],
				['1.5 - Iterazio Plana', '../Barne Informazioa/Barne Kudeaketa/iteration_plan_tpl.pdf'],
				['1.6 - Proiektu Plana', '../Barne Informazioa/Barne Kudeaketa/Project Plan.pdf'],
				['1.7 - Arrisku Zerrenda', '../Barne Informazioa/Barne Kudeaketa/risk_list_tpl.pdf'],
				['1.8 - Lan Atazen Zerrenda', '../Barne Informazioa/Barne Kudeaketa/work_items_list_tpl.pdf'],
				['1.9 - Proiektuko Artefaktuen Ziurtagiriak', '../Barne Informazioa/Barne Kudeaketa/Proiektuko Artefaktuen Ziurtagiriak.pdf'],
				['1.10 - Arriskuen Kudeaketa eta Analisia', '../Barne Informazioa/Barne Kudeaketa/Arriskuen Kudeaketa eta Analisia/Referencia.pdf',
					['1.10.1 - Analisi Goiztiarra', '../Barne Informazioa/Barne Kudeaketa/Arriskuen Kudeaketa eta Analisia/Alertas Tempranas.pdf'],
					['1.10.2 - Analisi Kualitatiboa', '../Barne Informazioa/Barne Kudeaketa/Arriskuen Kudeaketa eta Analisia/Analisis Cualitativo.pdf'],
					['1.10.3 - Analisi Kuantitatiboa', '../Barne Informazioa/Barne Kudeaketa/Arriskuen Kudeaketa eta Analisia/Analisis Cuantitativo.pdf']
				],
			],
      ['2 - Aurreko Proiektuen Webguneak', '../Barne Informazioa/Aurreko Proiektuen Webguneak/Aurreko Proiektuen Webguneak.pdf',
        ['2.1 - ProWF 2020', '../Barne Informazioa/Aurreko Proiektuen Webguneak/ProWF_Proiektua/index.html'],
        ['2.2 - BETRADOK 2019', 'http://158.227.114.222:8080/software-process/CURSO_MATERIALES/2019_BETRADOKweb/index.htm'],
        ['2.3 - EvDiscover 2017', 'http://158.227.114.222:8080/software-process/CURSO_MATERIALES/2017_EvDiscover/index.html'],
        ['2.4 - Gimex 2008', 'http://158.227.114.222:8080/software-process/CURSO_MATERIALES/2008_bpms_intalio_Itziar/index.htm'],
        ['2.5 - GesProsoft 2005', 'http://158.227.114.222:8080/software-process/CURSO_MATERIALES/PFC_GesProSoft_menu_ok/index.htm'],
      ],
			['3 - Aurreko Proiektuen Memoriak', '../Barne Informazioa/Aurreko Proiektuen Memoriak/Aurreko Proiektuen Memoriak.pdf',
        ['3.1 - ProWF 2020', '../Barne Informazioa/Aurreko Proiektuen Memoriak/ProWF.pdf'],
        ['3.2 - BETRADOK 2019', '../Barne Informazioa/Aurreko Proiektuen Memoriak/BETRADOK.pdf'],
        ['3.3 - EvDiscover 2017', '../Barne Informazioa/Aurreko Proiektuen Memoriak/EvDiscover.pdf'],
        ['3.4 - Gimex 2008', '../Barne Informazioa/Aurreko Proiektuen Memoriak/Gimex.pdf'],
        ['3.5 - GesProSoft 2005', '../Barne Informazioa/Aurreko Proiektuen Memoriak/GesProSoft.pdf'],
      ],
			['4 - Ingurunea', '../Barne Informazioa/Ingurunea/0_ingurunea.pdf',
				['4.1 - Garapen Prozesuaren Webgunea', '../Barne Informazioa/Ingurunea/Project Lifecycle/index.html'],
				['4.2 - Garapen Prozesua', '../Barne Informazioa/Ingurunea/Project Lifecycle.bpm'],
				['4.3 - Garapen Kasua', '../Barne Informazioa/Ingurunea/development_case_tpl.pdf'],
				['4.4 - Tresnak', '../Barne Informazioa/Ingurunea/tools.pdf',
					['4.4.1 - Proiektuen Elaborazio Aplikazioa', '../Barne Informazioa/Ingurunea/tools.pdf'],
					['4.4.2 - Osagaiak', '../Barne Informazioa/Ingurunea/tools.pdf'],
					['4.4.3 - Beste Erreminta Batzuk', '../Barne Informazioa/Ingurunea/tools.pdf'],
				],
				['4.5 - Garapen Prozesuaren Planifikazioa', '../Barne Informazioa/Ingurunea/Lanaren Planifikazioa.pdf'],
				['4.6 - Garapen Prozesuko Erabakien Justifikazioa', '../Barne Informazioa/Ingurunea/Erabakien Justifikazioa.pdf'],
				['4.7 - Garapen Prozesuren Inplementazio Ideiak', '../Barne Informazioa/Ingurunea/Inplementazio Ideiak.pdf'],
			],
			['5 - Trebatzeko Materialak', '../Barne Informazioa/Barne Kudeaketa/Trebatzeko Materialak/Trebatzeko Materialak.pdf'],
		]
	];